pipeline {
    agent any

    stages {
        stage('Clonage') {
            steps {
                git 'https://github.com/bahanivissiley/docker_cc_bahani_vissiley.git'
            }
        }

        stage('Construction de l\'image') {
            steps {
                sh 'docker build -t bahani_vissiley_dockerhub/mon_nom-flask-app .'
            }
        }

        stage('Publication sur Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
                    sh 'docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD'
                    sh 'docker push bahani_vissiley_dockerhub/bahani_vissiley-flask-app'
                }
            }
        }
    }
}